name: 'crypto_dbt'
version: '1.0.0'

profile: 'crypto_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  crypto_dbt:
    +materialized: table   # Default materialization for all models