version: 2

models:
  - name: dim_coin
    description: "Dimension table containing details of cryptocurrencies"
    columns:
      - name: coin_id
        description: "Unique identifier for the cryptocurrency"
        tests:
          - not_null
          - unique
      - name: name
        description: "Name of the cryptocurrency"
        tests:
          - not_null
      - name: symbol
        description: "Ticker symbol e.g. BTC for Bitcoin"
        tests:
          - not_null

  - name: fact_prices
    description: "Fact table containing daily prices of cryptocurrencies"
    meta:
      depends_on: 
        - 'dim_coin'
    columns:
      - name: coin_id
        description: "Unique identifier for the cryptocurrency"
        tests:
          - not_null
          - relationships:
              to: ref('dim_coin')
              field: coin_id
      - name: current_price
        description: "Current price in USD"
        tests:
          - not_null
      - name: market_cap
        description: "Market capitalization in USD"
        tests:
          - not_null
      - name: price_change_24h
        description: "Absolute price change in the last 24 hours"
        tests:
          - not_null
      - name: price_change_pct_24h
        description: "Percentage price change in the last 24 hours"
        tests:
          - not_null
      - name: price_date
        description: "Date the price was recorded"
        tests:
          - not_null